# Generated by Django 3.2.9 on 2021-12-01 15:49

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geom", django.contrib.gis.db.models.fields.PolygonField(srid=2056)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": " Plot",
            },
        ),
        migrations.CreateModel(
            name="SectorA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "  Level A sector",
            },
        ),
        migrations.CreateModel(
            name="SectorB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sylvis.sectora",
                    ),
                ),
            ],
            options={
                "verbose_name": "  Level B sector",
            },
        ),
        migrations.CreateModel(
            name="Treatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sylvis.plot"
                    ),
                ),
            ],
            options={
                "verbose_name": "Treatment",
            },
        ),
        migrations.CreateModel(
            name="SectorC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sylvis.sectorb",
                    ),
                ),
            ],
            options={
                "verbose_name": "  Level C sector",
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, default="")),
                ("volume", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sylvis.plot"
                    ),
                ),
            ],
            options={
                "verbose_name": "Section",
            },
        ),
        migrations.AddField(
            model_name="plot",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sylvis.sectorc",
            ),
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, default="")),
                ("vol_s_pied", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sylvis.plot"
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory",
            },
        ),
    ]
