# Generated by Django 3.2.9 on 2021-12-02 09:02

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sylvis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="etale",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="yearly_growth",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Yearly growth"
            ),
        ),
        migrations.AddField(
            model_name="sector",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sector",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sylvis.sector",
            ),
        ),
        migrations.AlterField(
            model_name="plot",
            name="geom",
            field=django.contrib.gis.db.models.fields.PolygonField(
                srid=2056, verbose_name="Geometry"
            ),
        ),
        migrations.AlterField(
            model_name="plot",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="plot",
            name="planned_next_section",
            field=models.DateField(
                blank=True, null=True, verbose_name="Next planned section"
            ),
        ),
        migrations.AlterField(
            model_name="plot",
            name="planned_next_treatment",
            field=models.DateField(
                blank=True, null=True, verbose_name="Next planned treatment"
            ),
        ),
        migrations.AlterField(
            model_name="plot",
            name="rotation_sections",
            field=models.IntegerField(default=0, verbose_name="Section rotation rate"),
        ),
        migrations.AlterField(
            model_name="plot",
            name="rotation_treatments",
            field=models.IntegerField(
                default=0, verbose_name="Treatment rotation rate"
            ),
        ),
    ]
