# Generated by Django 3.2.9 on 2021-12-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sylvis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="planned_next_section",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plot",
            name="planned_next_treatment",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plot",
            name="rotation_sections",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plot",
            name="rotation_treatments",
            field=models.IntegerField(default=0),
        ),
    ]
