# Generated by Django 3.2.9 on 2021-12-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sylvis', '0003_auto_20211202_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
