# Generated by Django 3.2.9 on 2021-12-02 11:00

from django.db import migrations


def rebuild_mptt(apps, schema_editor):
    from ..models import Sector

    Sector.objects.rebuild()


class Migration(migrations.Migration):

    dependencies = [
        ("sylvis", "0005_auto_20211202_1100"),
    ]

    operations = [
        migrations.RunPython(rebuild_mptt),
    ]
