# Generated by Django 3.2.9 on 2021-12-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sylvis", "0006_rebuild_mptttree"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventory",
            options={"ordering": ["date"], "verbose_name": "Inventory"},
        ),
        migrations.AlterModelOptions(
            name="section",
            options={"ordering": ["date"], "verbose_name": "Section"},
        ),
        migrations.AlterModelOptions(
            name="treatment",
            options={"ordering": ["date"], "verbose_name": "Treatment"},
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="remarks",
        ),
        migrations.RemoveField(
            model_name="section",
            name="remarks",
        ),
        migrations.RemoveField(
            model_name="treatment",
            name="description",
        ),
        migrations.RemoveField(
            model_name="treatment",
            name="remarks",
        ),
        migrations.AddField(
            model_name="inventory",
            name="remarks",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="section",
            name="remarks",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="treatment",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="treatment",
            name="remarks",
            field=models.TextField(blank=True, default=""),
        ),
    ]
