# Generated by Django 3.2.9 on 2021-12-02 16:42

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sylvis", "0007_auto_20211202_1234"),
    ]

    operations = [
        migrations.AddField(
            model_name="sector",
            name="computed_inventories_detail",
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="sector",
            name="computed_inventories_total",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="sector",
            name="computed_sections_detail",
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="sector",
            name="computed_sections_total",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="sector",
            name="computed_treatments_detail",
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="sector",
            name="computed_treatments_total",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="plot",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plots",
                to="sylvis.sector",
            ),
        ),
        migrations.AlterField(
            model_name="sector",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="sylvis.sector",
            ),
        ),
    ]
