# Generated by Django 3.2.9 on 2021-12-03 16:35

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.collections
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sylvis", "0009_dummymapmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="sector",
            name="computed_geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                default=django.contrib.gis.geos.collections.MultiPolygon,
                editable=False,
                srid=2056,
            ),
        ),
    ]
