# Generated by Django 3.2.10 on 2021-12-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sylvis", "0010_sector_computed_geom"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DummyMapModel",
        ),
    ]
