version: '3.7'

services:

  caddy:
    build:
      context: .
      dockerfile: docker/caddy/Dockerfile
    volumes:
      - caddy_data:/data
      - static_volume:/static_volume
      - media_volume:/media_volume
    restart: unless-stopped
    environment:
      SYLVIS_HOST: ${SYLVIS_HOST:?}
    ports:
      - 80:80
      - 443:443

  django:
    image: opengisch/sylvis-django:latest
    build:
      context: .
      dockerfile: docker/django/Dockerfile
      cache_from:
        - opengisch/sylvis-django:latest
    restart: unless-stopped
    volumes:
      - static_volume:/static_volume
      - media_volume:/media_volume
    environment:
      DJANGO_DEBUG: "false"
      SYLVIS_HOST: ${SYLVIS_HOST:?}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:?}
      DJANGO_STATIC_ROOT: /static_volume
      DJANGO_MEDIA_ROOT: /media_volume
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      TX_TOKEN: ${TX_TOKEN}
    command: python3 manage.py runserver 0.0.0.0:8000

  postgres:
    image: postgis/postgis:13-3.1
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
    restart: unless-stopped
    ## UNCOMMENT IF YOU NEED THE POSTGIS DATABASE TO BE ACCESSIBLE
    # ports:
    # - 5432:5432


volumes:
  static_volume:
  media_volume:
  caddy_data:
