name: Test Django Migrations

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1

    steps:

    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Django image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        pull: true
        cache-from: type=registry,ref=opengisch/sylvis-django:latest
        cache-to: type=registry,ref=opengisch/sylvis-django:latest,mode=max
        tags: opengisch/sylvis-django:latest

    - name: setup Docker
      run: |
        docker-compose up -d
        sleep 10

    - name: check migrations
      run: |
        docker-compose exec -T django python manage.py makemigrations --check

    - name: "failure logs"
      if: failure()
      run: |
        docker-compose logs
